title:            JeremyCollins.net
description:      Personal website for Jeremy Collins

# put your disqus here
disqus_shortname:
reading_time:     true # if true, shows the estimated reading time for a post
words_per_minute: 200
logo:             images/jcn-sm.png # logo visible in the topbar
excerpt_separator: <!--more-->
# Your site's domain goes here (eg: //mmistakes.github.io, http://mademistakes.com, etc)
# When testing locally leave blank or use http://localhost:4000

url: http://jeremycollins.net

# draw your top menu here
# each item must have a title and a url.
#   To list post categories. use type: 'categories'
#   To create sub categories. add a submenu item
# See the example
menu:
  - title: 'Home'
    url: '/'
  - title: 'About'
    url: '/about'
    type: 'about'
  - title: 'Github'
    url: 'https://github.com/jdodsoncollins'
  - title: 'Contact'
    url: '#'
    submenu:
      - title: 'LinkedIn'
        url: 'https://www.linkedin.com/in/jeremy-collins-37807911'
      - title: 'Twitter'
        url: 'https://twitter.com/jollins'

# Owner/author information
owner:
  name:           Jeremy Collins
  site:           http://jeremycollins.net
  avatar:         images/avatar.jpg
  bio:            "I'm a Software Engineer, most interested in developing attractive, fast, component-based progressive webapps. I also tinker with mobile app development for fun."
  email:          jeremy@jeremycollins.net
  # Twitter nick for use in Twitter cards and follow button.
  twitter: jollins # if no twitter in this config, the twitter follow button will be removed
  # GitHub nick for use in follow button in author block.
  github: jdodsoncollins

# Twitter account associated with the site if different from owner/author twitter account.
# Used in Twitter cards.
twitter: jdodsoncollins

# Social networking links used in author block underneath posts. Update and remove as you like.
social:
  - title: "github"
    url: "https://github.com/jdodsoncollins"
  - title: "linkedin"
    url: "https://www.linkedin.com/in/jeremy-collins-37807911"
#  - title: "youtube"
#    url: "https://www.youtube.com/channel/UCfnSek-9HPWOx5e2pH7VFgg"

# Background image to be tiled on all pages
background:

# Analytics and webmaster tools stuff goes here
google_analytics: UA-38793751-2
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/Los_Angeles
locale:      en_US
future:      true
highlighter: rouge
markdown:    kramdown
sass:
  sass_dir: _sass
  style: compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

# Amount of post to show on home page
paginate: 5

# if true, shows the floatting share buttons
float_share: true

# Octopress
# Default extensions
post_ext: md
page_ext: md
# Found in _templates/
post_layout: post
page_layout: page
# Format titles with titlecase?
titlecase: true

include: [".htaccess"]
exclude: ["demo/*", "lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
gems: [jekyll-paginate]
theme: neo-hpstr-jekyll-theme
